name: Test Workflow
on: [push]
jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: twincities-os/github-actions-examples@main
        with: 
          MODEL_VERSION: "v1.0"
      - uses: actions/checkout@v4
      - run: echo "mike was here"